fix: find correct permission
integrations/terraform-provider-github pull request #1230
Opened 2022-07-22 11:04 UTC by joshua-hancox

2022-07-29 07:55 UTC, SharpEdgeMarshall commented
With this PR you are removing the support for custom role permissions, am I right? We need that

2022-09-07 10:45 UTC, SharpEdgeMarshall commented
@joshua-hancox @kfcampbell any news? this is blocking us from adopting this provider

2022-09-12 14:06 UTC, Luis-3M commented
We're also interested in having this fix available - quiet confusing to see TF plans that always report changes when using custom roles.

2022-11-01 20:58 UTC, kfcampbell commented on github/resource_github_repository_collaborator.go
> +				ValidateFunc: validateValueFunc([]string{"pull", "triage", "push", "maintain", "admin"}),
The addition of this `ValidateFunc` means that custom roles can no longer be used, correct?

2022-11-01 21:51 UTC, nickfloyd commented
Hey @joshua-hancox I'd be glad to resolve those merge conflicts for you to move this along if you'd like.  I'll need push or maintainer access to [joshua-hancox:main](https://github.com/joshua-hancox/terraform-provider-github/tree/main), though so that we can get your fork synced with this repo.  Let us know if you'd like us to handle that or if you'd be up for doing it!

2022-11-02 10:04 UTC, joshua-hancox commented
@kfcampbell I don't believe that was part of my change here, sorry it's been ages since I looked at this.

@nickfloyd I doubt I have any time to look at this any time soon, I have added you as collaborator please feel free to carry on.

2022-11-02 10:09 UTC, SharpEdgeMarshall commented
From my understanding this PR https://github.com/integrations/terraform-provider-github/pull/1192 was good but didn't consider backwards compatibility.
May I propose to release a new major with those changes or add some kind of mapping to preserve old naming compatibility?

2022-11-09 18:52 UTC, kfcampbell approved these changes
I'll get this merged and released in the near future.

2022-11-09 18:57 UTC, kfcampbell requested changes
Ahh oops I should've looked at the checks before approving :facepalm: 

@joshua-hancox do you have any interest in fixing up the merge conflicts? If not, I can take a look at it at some point.

2022-11-10 21:40 UTC, kfcampbell commented
Sounds good! I've added the "Status: Up for grabs" label so the community can jump on the submission if anybody can get to it sooner rather than later.

2022-11-15 21:48 UTC, kfcampbell requested changes
I don't feel comfortable merging this PR given the diff/changes here. The commit history includes commits that I've force-pushed away, and I'm scared of reintroducing [this incident](https://github.com/integrations/terraform-provider-github/issues/1236#issuecomment-1198622552) merging this PR as-is. 

I'm going to close this for the time being, and would be very receptive to reviewing PRs that cherry-pick relevant commits or reimplement the functionality.

2022-11-15 21:48 UTC, kfcampbell commented
g

2022-11-15 21:48 UTC, closed without merging