Added encrypted_value to Actions + Organizations's secrets
integrations/terraform-provider-github pull request #807
Opened 2021-06-03 10:01 UTC by nadenf

Fixes:

#704 - Use encrypted_value in github_actions_organization_secret and github_actions_secret

2021-06-04 11:00 UTC, tibbes requested changes
Thanks for your pull requests @nadenf! I think @jcudit is going to post a fuller review shortly, but I just wanted to leave a quick note on the blocker for merging this.

2021-06-04 20:12 UTC, jcudit commented on github/data_source_github_repository_branches.go
> +package github
nvm, removed in 6880b90

2021-06-05 03:54 UTC, nadenf commented
@jcudit @tibbes  .. All changes made.

2021-06-07 20:38 UTC, tibbes approved these changes
Thanks @nadenf. 👍 on the base64 changes. I've also manually tested that using `encrypted_value` works (for repo-level secrets).

2021-06-07 20:46 UTC, tibbes commented
But we seem to have lost 6880b90a3cb40a95fa5501c461c7968849e99e9a (the commit that removes `data_source_github_repository_branches.go`)

2021-06-07 23:50 UTC, nadenf commented
@tibbes  .. File has been removed.

2021-06-07 23:55 UTC, jcudit approved these changes

2021-06-08 00:03 UTC, merged

2021-07-05 10:03 UTC, hoxu commented
Is there documentation somewhere on how to create the `encrypted_value` using the public key?

2021-07-22 20:54 UTC, jcudit commented
@hoxu a (hack) workaround would be to:
- configure your `_secret` resource using a `plaintext_value`
- `TF_LOG=DEBUG terraform apply ...` the configuration
- extract the encrypted and base64 encoded string that is sent to the GitHub API
- use the extracted value in the `encrypted_value` field going forward

I have not tried this personally but theoretically this should work if I am not overlooking something.

2021-08-20 05:48 UTC, hoxu commented
@jcudit thanks, this indeed works. But if you have remote state (especially with versioning), you need to manually comment out the backend, `terraform init`, do all this, enable the backend again and `terraform init`. In my opinion it's too cumbersome. And these steps are not documented on https://registry.terraform.io/providers/integrations/github/latest/docs/resources/actions_secret